version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./database/database.env
    ports:
      - "5432:5432"
    container_name: postgres_database
  
  faker-service:
    build: ./faker
    ports:
      - 5002:80
    container_name: datos_falsos_flask
  
  api-service:
    restart: always
    build: ./api
    ports:
      - 5001:80
    depends_on: 
      - db
    links:
      - db
    container_name: api_flask
  
  website:
    build: ./web
    ports:
      - 5000:80
    depends_on:
      - api-service
    container_name: website_flask
volumes:
  postgres_data:
